package webApp::Model::DB;

use strict;

use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'webApp::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:PForums',
        user => 'root',
        password => '',
    }
);

=head1 NAME

WebApp::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Tractivity::App>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<WebApp::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Ashutosh Kukreti

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;